---

- name: 1.1 ensures docker dirs
  file: path={{ item }} state=directory
  with_items:
   - /etc/systemd/system
   - /etc/docker
   - /var/lib/docker

- name: 1.2 create docker pv
  when:
   - docker_disk_names | default('') | length > 0
  lvg:
    vg: docker
    pvs: "{{ docker_disk_names }}"

- name: 1.3 prepare docker data disk
  when:
   - docker_disk_names | default('') | length > 0
  lvol:
    vg: docker
    lv: data
    size: 100%vg
    state: present
  register: create_lv_docker_data

- name: 1.4 format docker data disk
  when:
   - docker_disk_names | default('') | length > 0
   - create_lv_docker_data is defined
   - create_lv_docker_data.changed
  mount:
    src: /dev/mapper/docker-data
    path: /var/lib/docker
    fstype: "{{ FS_TYPE | default('xfs') }}"
    state: mounted

- name: 1.5 install docker binaries
  when: 
    - true
  unarchive:
    src: "{{ binary_cdn.docker }}"
    dest: /usr/local/bin
    remote_src: yes
    extra_opts:
        - --strip-components=1

- name: 1.6 config docker's config and service
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode | default('0644')}}
  with_items:
    - {src: docker.service.j2, dest: '/etc/systemd/system/docker.service'}
    - {src: seccomp.json, dest: '/etc/docker/seccomp.json'}
    - {src: daemon.json.j2, dest: '/etc/docker/daemon.json'}

- name: 1.7 try restart docker daemon
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes

- command: systemctl is-active etcd