---

- name: Printing the environmentâ€‹ variable in Ansible
  debug:
    msg: "ONEBOX_REGION => {{ ONEBOX_REGION }}."

- name: Hostname | Update the hostname (pt. 1) - hostname cmd
  hostname:
    name: "{{inventory_hostname_short}}"
  ignore_errors: yes

- name: Hostname | Update the hostname (pt. 2) - (/etc/hostname)
  copy:
    content: "{{ ONEBOX_REGION }}-{{inventory_hostname_short}}{{'\n'}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  ignore_errors: yes

- name: Hostname | Update the IPv4 hostname (pt. 3) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1{{'\t'}}{{ ONEBOX_REGION }}-{{inventory_hostname}}{% if inventory_hostname != inventory_hostname_short %}{{'\t'}}{{ ONEBOX_REGION }}-{{inventory_hostname_short}}{% endif %}{{'\t'}}localhost"
    state: present
  ignore_errors: yes